### ISSUE TITLE
`syscall.Statfs` not compatible with windows.

### ISSUE THREAD

**Issue by zQueal** [0l1v3rr/cli-file-manager#1]
**Describe the bug**
Cross compile for windows fails.

**To Reproduce**
1. Attempt to build for windows;

```
❯ GOOS=windows go build
# github.com/0l1v3rr/cli-file-manager/pkg
../../pkg/diskInfo.go:12:8: undefined: syscall.Statfs_t
../../pkg/diskInfo.go:13:9: undefined: syscall.Statfs
```

**Additional context**
I believe that `syscall.Statfs` isn't compatible with Windows. Any way this could be changed to something which would make cross-compilation possible?

**Comment by 0l1v3rr** [comment]
Hello,
First, thanks for submitting an issue.
You're right, the `syscall.Statfs` is not compatible with Windows.
I could surely find a way to make it work on it as well, but since this File Manager was designed for Linux, it may cause a lot of bugs and unexpected behaviors.
I'm currently not planning to make it cross-platform anyways.
